[package]
name = "rdenadai_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15"
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.97"
actix-web = "4"
sqlx = { version = "0.7", features = ["runtime-tokio", "postgres", "macros"] }
