version: "3.5"

services:
  api01: &api
    # image: docker.io/rdenadai/rinha-backend-2024q1:latest
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api01
    restart: on-failure
    environment:
      - DB_HOSTNAME=db
    ports:
      - "8081:8080"
    depends_on:
      - db
    volumes:
      - ./src:/src
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "155MB"

  api02:
    # Essa sintaxe reusa o que foi declarado em 'api01'.
    <<: *api
    hostname: api02
    environment:
      - DB_HOSTNAME=db
    ports:
      - "8082:8080"

  nginx:
    image: nginx:stable-alpine3.17-slim
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10MB"

  db:
    image: postgres:16.1-alpine3.19
    hostname: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c max_connections=150
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "230MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
