version: "3.8"

services:
  api01: &api
    image: thiagosousa/rinha-api:latest
    hostname: api01
    environment:
      - MONGO_URI=mongodb://username:password@mongodb:27017
      - MONGO_DB=rinha
    ports:
      - "8080:8080"
    depends_on:
      mongodb:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "200MB"
  api02:
    <<: *api
    hostname: api02
    environment:
      - MONGO_URI=mongodb://username:password@mongodb:27017
      - MONGO_DB=rinha
      - PORT=8081
    depends_on:
      - api01
    ports:
      - "8081:8081"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "10MB"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "140MB"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      retries: 30